# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main
variables:
  uiSource: "."
  uiBuild: "$(uiSource)"

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.14.0"
    displayName: "Install Node.js"

  - script: |
      pushd $(uiSource)
      rm -rf node_modules
      rm -f package-lock.json yarn.lock
      npm install --global yarn
      yarn
      yarn build
      echo "build run successfully"
      popd
    displayName: "npm install and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(uiBuild)/build"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
